name = "OptimizationProblems"
uuid = "cedb96af-b716-49a9-8995-d784cce4c15f"
authors = ["Vivak Patel <vp314@users.noreply.github.com>"]
version = "0.1.3"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OptimizationModels = "1e8ba084-2b82-410e-94da-52931dd80093"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Distributions = "0.25.118"
LinearAlgebra = "1"
OptimizationModels = "0.1.0"
Random = "1"
