name = "OptimizationProblems"
uuid = "cedb96af-b716-49a9-8995-d784cce4c15f"
authors = ["Vivak Patel <vp314@users.noreply.github.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OptimizationModels = "1e8ba084-2b82-410e-94da-52931dd80093"

[compat]
LinearAlgebra = "1"
OptimizationModels = "0.1.0"
